name = "LatexSVG"
uuid = "b81a8e73-d03d-4f31-826c-30040db55cb2"
authors = ["Jiaqi Bao <invisibleehb@outlook.com>"]
version = "0.3.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
EzXML = "1.1"
FixedPointDecimals = "0.3"
Preferences = "1.1"
julia = "1.6"
