name: CompatHelper
on:
    schedule:
        - cron: "0 0 * * 0"

jobs:
    CompatHelper:
        runs-on: ubuntu-latest
        steps:
            - uses: julia-actions/setup-julia@v1
            - run: julia -e 'import Pkg; Pkg.add("CompatHelper")'
            - run: julia -e 'import CompatHelper; CompatHelper.main()'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
